version: "3"

services:
  app:
    build: .
    container_name: "auth-app"
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    volumes:
      - .:/app

  postgres-db:
    image: postgres:latest
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres-db
    restart: on-failure